//just action types since strings are prone to duplicates.

//auth actions
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED'
export const LOGOUT_USER = 'LOGOUT_USER'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'
export const NETWORK_FAILURE = 'NETWORK_FAILURE'

//counter.
export const INCREASE_COUNTER = 'INCREASE_COUNTER'
export const DECREASE_COUNTER = 'DECREASE_COUNTER'
//customer
export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS'
export const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS'
export const FETCH_CUSTOMERS_FAILURE = 'FETCH_CUSTOMERS_FAILURE'
export const ADD_CUSTOMER_SUCCESS = 'ADD_CUSTOMER_SUCCESS'
export const ADD_CUSTOMER_FAILURE = 'ADD_CUSTOMER_FAILURE'
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS'
export const DELETE_CUSTOMER_FAILURE = 'DELETE_CUSTOMER_FAILURE'
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS'
export const UPDATE_CUSTOMER_FAILURE = 'UPDATE_CUSTOMER_FAILURE'
export const SHOW_NEW_CUSTOMER_FORM = 'SHOW_NEW_CUSTOMER_FORM'
export const HIDE_NEW_CUSTOMER_FORM = 'HIDE_NEW_CUSTOMER_FORM'
export const FETCH_CUSTOMERS_STATIC = 'FETCH_CUSTOMERS_STATIC'

//cats action types.
export const FETCH_CATS_SUCCESS = 'FETCH_CATS_SUCCESS'
export const FETCH_CATS_START = 'FETCH_CATS_START'
export const FETCH_CATS_ERROR = 'FETCH_CATS_ERROR'
export const ADOPT_CAT_SUCCESS = 'ADOPT_CAT_SUCCESS'
export const CHASE_CAT_SUCCESS = 'CHASE_CAT_SUCCESS'
export const UPDATE_CAT_SUCCESS = 'UPDATE_CAT_SUCCESS'

//customer orders
export const FETCH_ORDERS = 'FETCH_ORDERS'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE'
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS'
export const ADD_ORDER_FAILURE = 'ADD_ORDER_FAILURE'
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS'
export const DELETE_ORDER_FAILURE = 'DELETE_ORDER_FAILURE'
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS'
export const UPDATE_ORDER_FAILURE = 'UPDATE_ORDER_FAILURE'

